name: dash_flags
description: A package for displaying flags of countries and languages with a set of widgets and enums
version: 0.1.2
repository: https://github.com/moazelsawaf/dash_flags
issue_tracker: https://github.com/moazelsawaf/dash_flags/issues
screenshots:
  - description: Dash Flags Example GIF
    path: doc/assets/animated_example.webp

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0
  test: null

flutter:
  assets:
    - assets/svgs/flags/countries/
    - assets/svgs/flags/languages/
